### ISSUE TITLE
Support for dynamically adding <canvas> elements

### ISSUE THREAD

**Issue by dianxiang** [3Dparallax/insight#116]
Many WebGL applications will dynamically load the <canvas> element instead of having it on the page from the start (applications using React, ThreeJS, etc.). We should add a refresh button to the bar at the bottom of the devtools page and a refresh button on the "No context found page" to search again for a canvas after the page has loaded.

**Comment by jacobhamblin** [comment]
+ 1

**Comment by jacobhamblin** [comment]
I'm really looking forward to this feature, so I'm going to implement it and send a PR soon, if you don't mind.

**Comment by dianxiang** [comment]
Sounds good, thanks Jacob!

**Comment by ArielSaldana** [comment]
Still seeing the old error. 

"WebGL Insight
No contexts found on page. Please try refreshing your page."

**Comment by peter-scott** [comment]
I'm also still seeing this problem.

**Comment by akhilpandey** [comment]
Any updates on this ?

**Comment by rfcoder89** [comment]
Any more updates?

**Comment by lihas** [comment]
Installed it today. Got error "No contexts found on page. Click the refresh button to check again."
Nothing happens on clicking refresh button
