### ISSUE TITLE
Link to Chrome Webstore stopped working

### ISSUE THREAD

**Issue by dkaraush** [3Dparallax/insight#137]
Is it still available? Link from Readme.md doesn't work: https://chrome.google.com/webstore/detail/webgl-devtools/hobpbneiaagcbdcmpjmibpmibohpgiga?hl=en-US&authuser=0

> 404. That’s an error.
> The requested URL was not found on this server. That’s all we know.

**Comment by AaronMorais** [comment]
Hey @dkaraush, this project is deprecated and no longer available on the Chrome Web Store. You can use the source and manually install the extension if you’d like.
